const data=window.TOURNAMENT_DATA;let eventName='All Events',scoring='Handicap';
const body=document.querySelector('#standingsBody'),count=document.querySelector('#resultCount'),tableSearch=document.querySelector('#tableSearch'),globalSearch=document.querySelector('#globalSearch'),division=document.querySelector('#divisionFilter'),drawer=document.querySelector('#profileDrawer'),overlay=document.querySelector('#overlay');
const menuButton=document.querySelector('.menu-button'),mainNav=document.querySelector('#mainNav'),clearGlobalSearch=document.querySelector('#clearGlobalSearch'),standingsView=document.querySelector('#full-tournament'),leaderGrid=document.querySelector('#divisionLeaderGrid');
const backToTop=document.querySelector('#backToTop');
const leaderboardLabel=document.querySelector('#leaderboardLabel'),resultPeriod=document.querySelector('#resultPeriod');
const norm=s=>s.toLowerCase().replace(/[^a-z0-9]/g,'');
const allNames=[...new Set(data.flatMap(x=>x.members))].sort();
document.querySelector('#bowlerCount').textContent=`${allNames.length} bowlers`;
function individualEntries(name){const entries=[];data.forEach(x=>{if(x.event==='All Events')return;if(x.memberBreakdown){const m=x.memberBreakdown.find(y=>y.bowler===name);if(m)entries.push({...m,id:x.id,event:x.event,name:x.name,division:x.division,color:x.color,members:[name]})}else if(x.name===name)entries.push({...x})});return entries}
function allEventRows(){return data.filter(x=>x.event==='All Events').map((x,i)=>({...x,id:20000+i,city:'Official All Events ranking',profileEntries:individualEntries(x.name)}))}
function render(){const q=norm(tableSearch.value.trim());let rows=(eventName==='All Events'?allEventRows():data.filter(x=>x.event===eventName)).filter(x=>(division.value==='All'||x.division===division.value)&&norm(`${x.name} ${x.members.join(' ')}`).includes(q));rows.sort((a,b)=>scoring==='Scratch'?b.scratch-a.scratch:b.total-a.total);body.innerHTML=rows.map((x,i)=>`<tr><td><span class="place ${i<3?'top':''}">${i+1}</span></td><td><button class="bowler" data-id="${x.id}"><span class="avatar" style="--avatar:${x.color}">${x.initials}</span><span><strong>${x.name}</strong><small>${x.city||x.members.join(' / ')}</small></span></button></td><td><span class="division">${x.division}</span></td><td class="games">${x.games.length>3?`${x.games.length} games`:x.games.join(' / ')}</td><td>${x.scratch.toLocaleString()}</td><td><strong>${x.total.toLocaleString()}</strong></td><td><button class="arrow" data-id="${x.id}" aria-label="Open ${x.name} details">&rarr;</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">No matching results. Try another filter.</td></tr>';count.textContent=`${rows.length} ${eventName==='All Events'?'bowlers':'entries'}`;leaderboardLabel.textContent='Final tournament leaderboard';resultPeriod.textContent='Final rankings';}
function openProfile(id){
  const isBowler=Number(id)>=20000;
  const x=isBowler?allEventRows().find(y=>y.id===Number(id)):data.find(y=>y.id===Number(id));
  const entries=isBowler?x.profileEntries:[x];
  const max=Math.max(0,...x.games);
  const eyebrow=isBowler?'Individual bowler profile':`${x.event} entry`;
  const subtitle=isBowler?x.city:x.members.join(' / ');
  const firstLabel=isBowler?'Entries':'Event';
  const firstValue=isBowler?entries.length:x.event;
  const secondLabel=isBowler?'Events':'Members';
  const secondValue=isBowler?new Set(entries.map(e=>e.event)).size:x.members.length;
  const sectionTitle=isBowler?'Tournament results':'Official entry result';
  const perGameHdcp=e=>e.games.length?Math.round(e.hdcp/e.games.length):0;
  const breakdown=!isBowler&&x.memberBreakdown?`<section class="member-breakdown"><div class="drawer-title"><h3>Bowler breakdown</h3><span>Scratch / Handicap</span></div><div class="breakdown-head"><span>Bowler</span><span>Games & handicap</span><span>Scratch</span><span>HDCP</span></div>${x.memberBreakdown.map(m=>`<div class="breakdown-row"><span><b>${m.bowler}</b></span><span>${m.games.join(' / ')}<small>+${perGameHdcp(m)} HDCP/game</small></span><span>${m.scratch}</span><strong>${m.total}</strong></div>`).join('')}</section>`:'';
  document.querySelector('#drawerContent').innerHTML=`<div class="profile-head"><span class="avatar large" style="--avatar:${x.color}">${x.initials}</span><p class="eyebrow dark">${eyebrow}</p><h2>${x.name}</h2><p>${subtitle}</p></div><div class="profile-stats"><div><small>${firstLabel}</small><strong class="${isBowler?'':'stat-text'}">${firstValue}</strong></div><div><small>${secondLabel}</small><strong>${secondValue}</strong></div><div><small>High shown</small><strong>${max||'-'}</strong></div></div><section class="game-section"><div class="drawer-title"><h3>${sectionTitle}</h3><span>${isBowler?'Full tournament':'Final standings'}</span></div><div class="profile-results">${entries.map(e=>`<div><span><b>${e.event}</b><small>${e.name}</small></span><span>${e.games.join(' / ')}<small class="entry-handicap">+${perGameHdcp(e)} HDCP/game</small></span><strong>${e.total}</strong></div>`).join('')}</div></section>${breakdown}<p class="sample-note">Final unofficial tournament standings published July 2026.</p>`;
  overlay.hidden=false;
  drawer.classList.add('open');
  drawer.setAttribute('aria-hidden','false');
}
document.querySelectorAll('.event-tabs button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('.event-tabs .active').classList.remove('active');btn.classList.add('active');eventName=btn.dataset.event;division.value='All';render();}));[tableSearch,division].forEach(el=>el.addEventListener('input',render));document.querySelectorAll('.sort-button').forEach(btn=>btn.addEventListener('click',()=>{scoring=btn.dataset.sort;document.querySelectorAll('.sort-button').forEach(b=>{b.classList.toggle('active',b===btn);b.querySelector('span')?.remove()});btn.insertAdjacentHTML('beforeend',' <span aria-hidden="true">&darr;</span>');render()}));body.addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(b)openProfile(b.dataset.id)});
let searchJumpTimer;
function syncClearButton(){clearGlobalSearch.hidden=!globalSearch.value}
function jumpToSearchResults(){globalSearch.blur();showFullTournament();standingsView.scrollTo({top:0,behavior:'smooth'})}
globalSearch.addEventListener('input',()=>{clearTimeout(searchJumpTimer);eventName='All Events';document.querySelector('.event-tabs .active').classList.remove('active');document.querySelector('[data-event="All Events"]').classList.add('active');tableSearch.value=globalSearch.value;syncClearButton();render();if(globalSearch.value.trim())searchJumpTimer=setTimeout(jumpToSearchResults,1200)});
globalSearch.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();clearTimeout(searchJumpTimer);jumpToSearchResults()}});
clearGlobalSearch.addEventListener('click',()=>{clearTimeout(searchJumpTimer);globalSearch.value='';tableSearch.value='';syncClearButton();render();globalSearch.focus()});
menuButton.addEventListener('click',()=>{const open=mainNav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));menuButton.textContent=open?'Close':'Menu'});
mainNav.addEventListener('click',()=>{mainNav.classList.remove('open');menuButton.setAttribute('aria-expanded','false');menuButton.textContent='Menu'});
function renderDivisionLeaders(){
  const groups=[['Singles - Men','Singles','Men'],['Singles - Women','Singles','Women'],['Doubles - Men','Doubles','Men'],['Doubles - Women','Doubles','Women'],['Mixed Doubles','Mixed Doubles','Mixed'],['Teams - Men','Teams','Men'],['Teams - Women','Teams','Women'],['Teams - Mixed','Teams','Mixed'],['Senior Singles - Men','Senior','Men - Singles'],['Senior Singles - Women','Senior','Women - Singles'],['Senior Doubles - Men','Senior','Men - Doubles'],['Senior Doubles - Women','Senior','Women - Doubles'],['Senior Teams - Mixed','Senior','Mixed - Teams']];
  leaderGrid.innerHTML=groups.map(([label,event,div])=>{const rows=data.filter(x=>x.event===event&&x.division===div).sort((a,b)=>b.total-a.total).slice(0,5);return `<article class="leader-card"><div class="leader-card-title"><span>${event}</span><h3>${label}</h3></div><ol>${rows.map((x,i)=>`<li><button data-id="${x.id}"><span class="leader-rank">${i+1}</span><span><strong>${x.name}</strong><small>${x.members.join(' / ')}</small></span><b>${x.total.toLocaleString()}</b></button></li>`).join('')||'<li class="leader-empty">No results yet</li>'}</ol></article>`}).join('');
}
function showFullTournament(e){if(e)e.preventDefault();standingsView.hidden=false;document.body.classList.add('standings-open');standingsView.scrollTop=0;syncBackToTop()}
function hideFullTournament(){standingsView.hidden=true;document.body.classList.remove('standings-open');syncBackToTop()}
document.querySelectorAll('a[href="#full-tournament"]').forEach(link=>link.addEventListener('click',showFullTournament));document.querySelector('#closeFullTournament').addEventListener('click',hideFullTournament);leaderGrid.addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(b)openProfile(b.dataset.id)});
function syncBackToTop(){backToTop.hidden=(standingsView.hidden?window.scrollY:standingsView.scrollTop)<450}
window.addEventListener('scroll',syncBackToTop,{passive:true});standingsView.addEventListener('scroll',syncBackToTop,{passive:true});
backToTop.addEventListener('click',()=>{(standingsView.hidden?window:standingsView).scrollTo({top:0,behavior:'smooth'})});
function closeProfile(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');overlay.hidden=true}document.querySelector('#closeDrawer').addEventListener('click',closeProfile);overlay.addEventListener('click',closeProfile);document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement.tagName!=='INPUT'){e.preventDefault();globalSearch.focus()}if(e.key==='Escape'){closeProfile();hideFullTournament();mainNav.classList.remove('open')}});
const info=window.TOURNAMENT_INFO;document.querySelector('#tournamentInfo').innerHTML=`<article class="info-card wide"><small>When & where</small><h3>${info.dates}</h3><p>${info.location}</p><strong>${info.entry}</strong></article><article class="info-card"><small>Event details</small><h3>Format & handicap</h3><p>${info.rules}</p></article><article class="info-card"><small>Senior division</small><h3>Ages 55+</h3><p>${info.senior}</p></article><article class="info-card wide"><small>Squad times</small><h3>Choose your squad</h3><ul>${info.squads.map(s=>`<li>${s}</li>`).join('')}</ul></article><article class="info-card"><small>Special squad</small><h3>Friday night prize</h3><p>${info.special}</p></article><article class="info-card"><small>Contact</small><h3>Questions & entry forms</h3><p><a class="contact-link" href="https://www.facebook.com/share/g/18ezY5PLi2/?mibextid=wwXIfr" target="_blank" rel="noopener noreferrer">Omaha TNBA Facebook page</a><br><a class="contact-link" href="mailto:omahatnba@yahoo.com">omahatnba@yahoo.com</a><br>Julius: <a class="contact-link" href="tel:+14026694952">(402) 669-4952</a></p><strong>${info.leaders}</strong></article>`;render();renderDivisionLeaders();
