const data=window.TOURNAMENT_DATA;let eventName='All Bowlers',scoring='Handicap';
const body=document.querySelector('#standingsBody'),count=document.querySelector('#resultCount'),tableSearch=document.querySelector('#tableSearch'),globalSearch=document.querySelector('#globalSearch'),division=document.querySelector('#divisionFilter'),scoreFilter=document.querySelector('#scoreFilter'),drawer=document.querySelector('#profileDrawer'),overlay=document.querySelector('#overlay');
const norm=s=>s.toLowerCase().replace(/[^a-z0-9]/g,'');
const allNames=[...new Set(data.flatMap(x=>x.members))].sort();
document.querySelector('#bowlerCount').textContent=`${allNames.length} bowlers`;
function bowlerRows(){return allNames.map((name,i)=>{const entries=data.filter(x=>x.members.includes(name)&&x.event!=='Senior');const best=entries.sort((a,b)=>b.total-a.total)[0];return{id:10000+i,name,members:[name],event:'All Bowlers',division:entries.find(x=>x.name===name)?.division||'Open',games:entries.flatMap(x=>x.name===name?x.games:[]),scratch:entries.reduce((n,x)=>n+x.scratch,0),hdcp:entries.reduce((n,x)=>n+x.hdcp,0),total:entries.reduce((n,x)=>n+x.total,0),city:`${entries.length} result ${entries.length===1?'entry':'entries'}`,initials:name.split(' ').map(n=>n[0]).slice(0,2).join(''),color:best?.color||'#477bbd',profileEntries:entries};});}
function render(){const q=norm(tableSearch.value.trim());let rows=(eventName==='All Bowlers'?bowlerRows():data.filter(x=>x.event===eventName)).filter(x=>(division.value==='All'||x.division===division.value||eventName==='All Bowlers')&&norm(`${x.name} ${x.members.join(' ')}`).includes(q));rows.sort((a,b)=>scoring==='Scratch'?b.scratch-a.scratch:b.total-a.total);body.innerHTML=rows.map((x,i)=>`<tr><td><span class="place ${i<3?'top':''}">${i+1}</span></td><td><button class="bowler" data-id="${x.id}"><span class="avatar" style="--avatar:${x.color}">${x.initials}</span><span><strong>${x.name}</strong><small>${x.city||x.members.join(' / ')}</small></span></button></td><td><span class="division">${x.division}</span></td><td class="games">${x.games.length>3?`${x.games.length} games`:x.games.join(' / ')}</td><td>${x.scratch.toLocaleString()}</td><td>+${x.hdcp}</td><td><strong>${x.total.toLocaleString()}</strong></td><td><button class="arrow" data-id="${x.id}" aria-label="Open ${x.name} details">&rarr;</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty">No matching results. Try another filter.</td></tr>';count.textContent=`${rows.length} ${eventName==='All Bowlers'?'bowlers':'entries'}`;}
function openProfile(id){
  const isBowler=Number(id)>=10000;
  const x=isBowler?bowlerRows().find(y=>y.id===Number(id)):data.find(y=>y.id===Number(id));
  const entries=isBowler?x.profileEntries:[x];
  const max=Math.max(0,...x.games);
  const eyebrow=isBowler?'Individual bowler profile':`${x.event} entry`;
  const subtitle=isBowler?x.city:x.members.join(' / ');
  const firstLabel=isBowler?'Entries':'Event';
  const firstValue=isBowler?entries.length:x.event;
  const secondLabel=isBowler?'Events':'Members';
  const secondValue=isBowler?new Set(entries.map(e=>e.event)).size:x.members.length;
  const sectionTitle=isBowler?'Tournament results':'Official entry result';
  document.querySelector('#drawerContent').innerHTML=`<div class="profile-head"><span class="avatar large" style="--avatar:${x.color}">${x.initials}</span><p class="eyebrow dark">${eyebrow}</p><h2>${x.name}</h2><p>${subtitle}</p></div><div class="profile-stats"><div><small>${firstLabel}</small><strong class="${isBowler?'':'stat-text'}">${firstValue}</strong></div><div><small>${secondLabel}</small><strong>${secondValue}</strong></div><div><small>High shown</small><strong>${max||'-'}</strong></div></div><section class="game-section"><div class="drawer-title"><h3>${sectionTitle}</h3><span>First weekend</span></div><div class="profile-results">${entries.map(e=>`<div><span><b>${e.event}</b><small>${e.name}</small></span><span>${e.games.join(' / ')}</span><strong>${e.total}</strong></div>`).join('')}</div></section>${!isBowler&&x.members.length>1?`<div class="member-note"><strong>Members</strong><p>${x.members.join(' and ')}</p><small>Open All Bowlers to view either person's full tournament history.</small></div>`:''}<p class="sample-note">Official first-week results published July 19, 2026.</p>`;
  overlay.hidden=false;
  drawer.classList.add('open');
  drawer.setAttribute('aria-hidden','false');
}
document.querySelectorAll('.event-tabs button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('.event-tabs .active').classList.remove('active');btn.classList.add('active');eventName=btn.dataset.event;division.value='All';render();}));[tableSearch,division,scoreFilter].forEach(el=>el.addEventListener('input',()=>{scoring=scoreFilter.value;render();}));body.addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(b)openProfile(b.dataset.id)});globalSearch.addEventListener('input',()=>{eventName='All Bowlers';document.querySelector('.event-tabs .active').classList.remove('active');document.querySelector('[data-event="All Bowlers"]').classList.add('active');tableSearch.value=globalSearch.value;document.querySelector('#standings').scrollIntoView({behavior:'smooth'});render();});function closeProfile(){drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');overlay.hidden=true}document.querySelector('#closeDrawer').addEventListener('click',closeProfile);overlay.addEventListener('click',closeProfile);document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement.tagName!=='INPUT'){e.preventDefault();globalSearch.focus()}if(e.key==='Escape')closeProfile()});
const info=window.TOURNAMENT_INFO;document.querySelector('#tournamentInfo').innerHTML=`<article class="info-card wide"><small>When & where</small><h3>${info.dates}</h3><p>${info.location}</p><strong>${info.entry}</strong></article><article class="info-card"><small>Event details</small><h3>Format & handicap</h3><p>${info.rules}</p></article><article class="info-card"><small>Senior division</small><h3>Ages 55+</h3><p>${info.senior}</p></article><article class="info-card wide"><small>Squad times</small><h3>Choose your squad</h3><ul>${info.squads.map(s=>`<li>${s}</li>`).join('')}</ul></article><article class="info-card"><small>Special squad</small><h3>Friday night prize</h3><p>${info.special}</p></article><article class="info-card"><small>Contact</small><h3>Questions & entry forms</h3><p><a class="contact-link" href="https://www.facebook.com/share/g/18ezY5PLi2/?mibextid=wwXIfr" target="_blank" rel="noopener noreferrer">Omaha TNBA Facebook page</a><br><a class="contact-link" href="mailto:omahatnba@yahoo.com">omahatnba@yahoo.com</a><br>Julius: <a class="contact-link" href="tel:+14026694952">(402) 669-4952</a></p><strong>${info.leaders}</strong></article>`;render();
